compressionLevel: mixed

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableImmutableInstalls: false

enableProgressBars: true

enableScripts: true

enableStrictSsl: false

nodeLinker: pnp

pnpEnableEsmLoader: true

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-4.10.0.cjs
