services:
    portfolio:
        build:
            context: .
            dockerfile: Dockerfile

        image: portfolio:1.0.0
        container_name: portfolio
        restart: unless-stopped

        ports:
            - '4200:8484'
        networks:
            - dev_net

networks:
    dev_net:
        name: development_network
        external: true
